framework: loxia
projectPath: frameworks/loxia
version: 0.2.0

description: A lightweight Dart ORM for Relational Databases built to be simple and extensible.
publisher: Avesbox
publisherUrl: https://avesbox.com
repository: https://github.com/avesbox/loxia
homepage: https://loxia.avesbox.com

build:
  command: dart
  args: ["build", "cli", "-o", "build/loxia"]

run:
  command: build/loxia/bundle/bin/loxia_bench
  args: []
  env: {}
